# Descriptive Statistic

In [1]:
x=[1,2,3,4,4,5,6,7,8,9]

In [2]:
import numpy as np
import pandas as pd

In [6]:
import math
import statistics
import scipy.stats

# 

In [8]:
x=[8.0,1,2.5,4,20.0]
x_with_nan=[8.0,1,2.5,math.nan,20.0]

In [9]:
x

[8.0, 1, 2.5, 4, 20.0]

In [10]:
x_with_nan

[8.0, 1, 2.5, nan, 20.0]

In [11]:
y,y_with_nan=np.array(x),np.array(x_with_nan)

In [13]:
z,z_with_nan=pd.Series(x),pd.Series(x_with_nan)

In [14]:
print(y)
print(y_with_nan)
print(z)
print(z_with_nan)

[ 8.   1.   2.5  4.  20. ]
[ 8.   1.   2.5  nan 20. ]
0     8.0
1     1.0
2     2.5
3     4.0
4    20.0
dtype: float64
0     8.0
1     1.0
2     2.5
3     NaN
4    20.0
dtype: float64


In [20]:
mean_=sum(x)/len(x)
mean_

7.1

In [21]:
mean_=sum(x_with_nan)/len(x_with_nan)
mean_

nan

In [23]:
statistics.mean(x)


7.1

In [22]:
statistics.mean(x_with_nan)

nan

In [28]:
xbar1=np.mean(x)
xbar2=np.nanmean(x_with_nan)
print(xbar1)
print(xbar2)

7.1
7.875


In [31]:
zbar1=np.mean(z_with_nan) #nan pd.series akan otomatis dilewat
print(zbar1)

7.875


In [32]:
w=[0.1,0.2,0.3,0.25,0.15]

In [33]:
wmean=sum(w[i] *x[i] for i in range(len(x)))/sum(w)
print(wmean)

5.75


In [34]:
wmean=sum(x_ *w_ for (x_,w_) in zip(x,w))/sum(w)
print(wmean)

5.75


In [35]:
y,z,w=np.array(x),pd.Series(x),np.array(w)
wmean=np.average(y,weights=w)
print(wmean)

5.75


In [36]:
(w*y).sum()/w.sum()

5.75

## Harmonic Mean

In [39]:
x

[8.0, 1, 2.5, 4, 20.0]

In [40]:
len(x)

5

In [41]:
len(x)/sum(1/i for i in x)

2.73972602739726

In [42]:
statistics.harmonic_mean(x)

2.73972602739726

In [43]:
scipy.stats.hmean(y)

2.73972602739726

## Geometric Mean

In [44]:
gmean=1
for item in x:
    gmean*=item

gmean**=1/len(x)
gmean

4.3734482957731124

In [45]:
scipy.stats.gmean(y)

4.373448295773112

# Median

In [48]:
n=len(x)
if n%2: #cek apakah genap
    median_=sorted(x)[round(0.5*(n-1))] #jika genap
else:
    x_ord,index=sorted(x), round(0.5*n)
    median_=0.5*x_ord[index-1]+x_ord[index]
print(x)
print(n)
print(median_)

[8.0, 1, 2.5, 4, 20.0]
5
4


In [51]:
a=[8,1,2.5,4]

In [52]:
statistics.median_low(a)

2.5

In [53]:
statistics.median_high(a)

4

In [54]:
statistics.median(a)

3.25

In [55]:
statistics.median(x_with_nan)

8.0

In [56]:
np.median(x)

4.0

# Mode

In [57]:
v=[12,15,12,12,17,14,13]

In [58]:
mode_=max((v.count(item),item) for item in set(v))
mode_

(3, 12)

In [59]:
statistic.mode(v)

NameError: name 'statistic' is not defined

In [61]:
mode_=scipy.stats.mode(v)
print(mode_.mode)
print(mode_.count)

[12]
[3]


In [62]:
pd.Series(v).mode()

0    12
dtype: int64

# Measures of Variability

In [63]:
n=len(x)
mean_=sum(x)/n
var_=sum((item-mean_) **2 for item in x)/(n-1)
var_


58.8

In [64]:
statistics.variance(x)

58.8

In [65]:
np.var(y,ddof=1)

58.8

## Standard deviation

In [67]:
std_=var_**0.5
std_

7.6681158050723255

In [68]:
statistics.stdev(x)

7.6681158050723255

In [69]:
np.std(y,ddof=1)

7.6681158050723255

## skewness

In [74]:
skew_=(sum((item-mean_)**3 for item in x)*n/((n-1)*(n-2)*std_**3))
skew_

1.6572122671680802

## percentile

In [79]:
statistics.quantiles(x,n =2)

[4.0]

In [78]:
statistics.quantiles(x,n=2,method='inclusive')

[4.0]

In [80]:
np.percentile(x,5)

1.3

## Ranges

In [81]:
#selisih max dengan min
np.ptp(x)

19.0

In [85]:
np.amax(x)-np.amin(x)

19.0

In [86]:
quartiles=np.quantile(y,[0.25,0.75])
quartiles[1]-quartiles[0]

5.5

# Summary of Descriptive Stat

In [87]:
result=scipy.stats.describe(y,ddof=1,bias=False)
result

DescribeResult(nobs=5, minmax=(1.0, 20.0), mean=7.1, variance=58.8, skewness=1.6572122671680796, kurtosis=2.7079320248507557)

In [88]:
result.nobs
result.minmax[0] #min
result.minmax[1] #max
result.mean
result.variance
result.skewness
result.kurtosis

2.7079320248507557

In [89]:
result=z.describe() #untuk pd series

In [90]:
result

count     5.000000
mean      7.100000
std       7.668116
min       1.000000
25%       2.500000
50%       4.000000
75%       8.000000
max      20.000000
dtype: float64

In [91]:
result['count']

5.0

In [92]:
result['max']

20.0

## Correlation

In [93]:
x=list(range(-10,11))
y=[0,2,2,2,2,3,3,6,7,4,7,6,6,9,4,5,5,10,11,12,14]
x_, y_=np.array(x),np.array(y)
x__,y__=pd.Series(x),pd.Series(y)

In [94]:
n1,n2=len(x),len(y)
mean_x, mean_y=sum(x)/n1,sum(y)/n2
cov_xy=(sum((x[k]-mean_x)*(y[k]-mean_y) for k in range(n1))/(n1-1))
cov_xy

19.95

In [95]:
np.cov(x_,y_)

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [97]:
x_.var(ddof=1)


38.5

In [98]:
y_.var(ddof=1)

13.914285714285711

In [100]:
cov_xy=x__.cov(y__) #pandas series
cov_xy

19.95

## Correlation Coefficient

In [101]:
r,p=scipy.stats.pearsonr(x_,y_)

In [104]:
r # correlation coefficient

0.861950005631606

In [105]:
p #p value

5.122760847201171e-07

In [106]:
corr_matrix=np.corrcoef(x_,y_)
corr_matrix

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])

In [109]:
scipy.stats.linregress(x_,y_)

LinregressResult(slope=0.5181818181818181, intercept=5.714285714285714, rvalue=0.861950005631606, pvalue=5.122760847201164e-07, stderr=0.06992387660074979, intercept_stderr=0.4234100995002589)

In [110]:
result=scipy.stats.linregress(x_,y_)
result.rvalue

0.861950005631606

In [111]:
result.slope

0.5181818181818181

## Working with 2D data

In [112]:
a=np.array([[1,1,1],
            [2,3,1],
            [4,9,2],
            [8,27,4],
            [16,1,1]
    
])

In [128]:
a

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [114]:
np.mean(a)

5.4

In [115]:
a.mean()

5.4

In [116]:
np.median(a)

2.0

In [117]:
a.var(ddof=1)

53.40000000000001

In [118]:
np.mean(a,axis=0) #across all row

array([6.2, 8.2, 1.8])

In [119]:
np.mean(a,axis=1) #across all column

array([ 1.,  2.,  5., 13.,  6.])

In [120]:
np.median(a,axis=0) #across all row

array([4., 3., 1.])

In [121]:
a.var(axis=0,ddof=1) #across all row

array([ 37.2, 121.2,   1.7])

In [122]:
scipy.stats.gmean(a) #default axis 0

array([4.        , 3.73719282, 1.51571657])

In [123]:
scipy.stats.gmean(a,axis=0)

array([4.        , 3.73719282, 1.51571657])

In [124]:
scipy.stats.gmean(a,axis=1)

array([1.        , 1.81712059, 4.16016765, 9.52440631, 2.5198421 ])

In [125]:
scipy.stats.gmean(a,axis=None)

2.829705017016332

In [126]:
scipy.stats.describe(a,axis=None,ddof=1,bias=False)

DescribeResult(nobs=15, minmax=(1, 27), mean=5.4, variance=53.40000000000001, skewness=2.264965290423389, kurtosis=5.212690982795767)

## Dataframe

In [129]:
row_names=['first','second','third','fourth','fifth']
col_names=['A','B','C']
df=pd.DataFrame(a,index=row_names,columns=col_names)
df

A   B  C
first    1   1  1
second   2   3  1
third    4   9  2
fourth   8  27  4
fifth   16   1  1

In [130]:
df.mean()

A    6.2
B    8.2
C    1.8
dtype: float64

In [131]:
df.var()

A     37.2
B    121.2
C      1.7
dtype: float64

In [132]:
df.mean(axis=1)

first      1.0
second     2.0
third      5.0
fourth    13.0
fifth      6.0
dtype: float64

In [133]:
df['A'].mean()

6.2

In [134]:
df['A'].var()

37.20000000000001

In [135]:
df.values

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [136]:
df.to_numpy()

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [137]:
df.describe()

A          B        C
count   5.00000   5.000000  5.00000
mean    6.20000   8.200000  1.80000
std     6.09918  11.009087  1.30384
min     1.00000   1.000000  1.00000
25%     2.00000   1.000000  1.00000
50%     4.00000   3.000000  1.00000
75%     8.00000   9.000000  2.00000
max    16.00000  27.000000  4.00000

In [138]:
df.describe().at['mean','A']

6.2

In [139]:
df.describe().at['50%','C']

1.0

# Visualizing Data

In [140]:
import matplotlib.pyplot as plt
plt.style.use('ggplot')

## Box plots

In [ ]:
np.random.seed(seed=0)