In [4]:
import numpy

In [5]:
numpy.__version__

'1.20.1'

In [1]:
import numpy as np

In [7]:
a=np.array([[1,2,3,4],[0,0,0,0],[1,1,1,1]])

In [8]:
a

array([[1, 2, 3, 4],
       [0, 0, 0, 0],
       [1, 1, 1, 1]])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [11]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## add, remove, and sort

In [14]:
arr=np.array([1,2,3,4,5])

In [15]:
arr=np.append(arr,[6,7])

In [16]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
arr=np.delete(arr,1)

In [18]:
arr

array([1, 3, 4, 5, 6, 7])

In [19]:
np.sort(arr)

array([1, 3, 4, 5, 6, 7])

## Shape and size

In [20]:
array1=np.array([[[0,1,2,3],
                 [4,5,6,7]],
                [[0,1,2,3],
                 [4,5,6,7]],
                [[0,1,2,3],
                 [4,5,6,7]],])

In [21]:
array1

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [22]:
array1.ndim
array1.size
array1.shape

(3, 2, 4)

In [23]:
array1.ndim

3

In [24]:
array1.size

24

## Reshape

In [25]:
array2=np.arange(6)

In [26]:
array2.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [27]:
array2.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Convert 1D to 2D

In [28]:
a=np.array([1,2,3,4,5,6])

In [29]:
a2=a[np.newaxis]

In [30]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [31]:
a

array([1, 2, 3, 4, 5, 6])

In [32]:
a2[0][0]

1

In [33]:
rowV=a[np.newaxis,:]
print(rowV.shape)
print(rowV)

(1, 6)
[[1 2 3 4 5 6]]


In [34]:
colV=a[:,np.newaxis]
print(colV.shape)
print(colV)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## indexing and slicing

In [47]:
data=np.array([1,2,3,4,5,6,7,8,9])

In [48]:
data[2]

3

In [49]:
data[0:2]

array([1, 2])

In [50]:
data[-2:]

array([8, 9])

In [51]:
three_up=(data>=2)

In [53]:
print(data[three_up])
print(data[data>=2])

[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [54]:
#select elements that meet certain criteria
divisible_by_2=data[data%2==0]
print(divisible_by_2)

[2 4 6 8]


In [56]:
#select elements that meet multiple criterias
criteria=data[(data%2==0) & (data>5)]
print(criteria)

[6 8]


## Creating Array from Existing Data

In [62]:
#stacking an array
a1=np.array([[1,2],
             [3,3]])
a2=np.array([[5,5],
             [8,8]])
a=np.vstack((a1,a2))
print(a)

[[1 2]
 [3 3]
 [5 5]
 [8 8]]


In [63]:
h=np.hstack((a1,a2))
print(h)

[[1 2 5 5]
 [3 3 8 8]]


In [67]:
#membagi array menjadi sejumlah array yg seukuran
splith=np.hsplit(h,2)
print(splith)

[array([[1, 2],
       [3, 3]]), array([[5, 5],
       [8, 8]])]


In [68]:
splith[1]

array([[5, 5],
       [8, 8]])

In [71]:
b=data.view()
c=data.copy()
print(b)
print(c)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


## Basic Array Operations

In [2]:
a=np.array([[1,2],[3,4]])

In [3]:
a

array([[1, 2],
       [3, 4]])

In [6]:
# add all of the elements in the array
a.sum()

10

In [9]:
#sum column
a.sum(axis=0)

array([4, 6])

In [10]:
#sum row
a.sum(axis=1)

array([3, 7])

In [22]:
b=np.ones(2)
ones=np.vstack((b,b))

In [23]:
ones

array([[1., 1.],
       [1., 1.]])

In [24]:
#sum array with same size
a+ones

array([[2., 3.],
       [4., 5.]])

In [37]:
#setiap element matriks dikalikan dengan dirinya sendiri
a*a

array([[ 1,  4],
       [ 9, 16]])

In [26]:
a/a

array([[1., 1.],
       [1., 1.]])

In [27]:
a*1.5

array([[1.5, 3. ],
       [4.5, 6. ]])

In [28]:
a.max()

4

In [29]:
a.min()

1

# Matrices

In [30]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
r=np.random.random((3,2))

In [33]:
r

array([[0.80956731, 0.15887514],
       [0.58008767, 0.69397576],
       [0.6196593 , 0.69216565]])

In [35]:
#sum each row in matrices with a vector
one_row=np.ones((1,2))
one_row

array([[1., 1.]])

In [36]:
print(r+one_row)

[[1.80956731 1.15887514]
 [1.58008767 1.69397576]
 [1.6196593  1.69216565]]


In [39]:
#perkalian matriks
a=np.array([[1,2,3],[2,2,2]])
b=np.array([[1,1],[2,2],[3,3]])
np.dot(a,b)

array([[14, 14],
       [12, 12]])

In [40]:
#transpose matriks
print("a:",a)
print("transpose a:",a.T)

a: [[1 2 3]
 [2 2 2]]
transpose a: [[1 2]
 [2 2]
 [3 2]]


In [41]:
#create array of six, dengan shape 2x3
arr=np.arange(6).reshape((2,3))

In [42]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
#mengubah matriks menjadi array
arrflat=arr.flatten()

In [44]:
arrflat

array([0, 1, 2, 3, 4, 5])